/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "messaging.h"

bool_t
xdr_Message (XDR *xdrs, Message *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->sender, 100))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->recipient, 100))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->text, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->timestamp, 32))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MessageArray (XDR *xdrs, MessageArray *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->messages.messages_val, (u_int *) &objp->messages.messages_len, ~0,
		sizeof (Message), (xdrproc_t) xdr_Message))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RegisterRequest (XDR *xdrs, RegisterRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->client_name, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SendMessageRequest (XDR *xdrs, SendMessageRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->sender, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->recipient, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->text, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_FetchMessageRequest (XDR *xdrs, FetchMessageRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->client_name, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_FetchMessageResponse (XDR *xdrs, FetchMessageResponse *objp)
{
	register int32_t *buf;

	 if (!xdr_MessageArray (xdrs, &objp->messageArray))
		 return FALSE;
	return TRUE;
}
