/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MESSAGING_H_RPCGEN
#define _MESSAGING_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Message {
	char *sender;
	char *recipient;
	char *text;
	char *timestamp;
};
typedef struct Message Message;

struct MessageArray {
	struct {
		u_int messages_len;
		Message *messages_val;
	} messages;
	int count;
};
typedef struct MessageArray MessageArray;

struct RegisterRequest {
	char *client_name;
};
typedef struct RegisterRequest RegisterRequest;

struct SendMessageRequest {
	char *sender;
	char *recipient;
	char *text;
};
typedef struct SendMessageRequest SendMessageRequest;

struct FetchMessageRequest {
	char *client_name;
};
typedef struct FetchMessageRequest FetchMessageRequest;

struct FetchMessageResponse {
	MessageArray messageArray;
};
typedef struct FetchMessageResponse FetchMessageResponse;

#define MESSAGING_PROG 0x20000001
#define MESSAGING_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define register_client 1
extern  int * register_client_1(RegisterRequest *, CLIENT *);
extern  int * register_client_1_svc(RegisterRequest *, struct svc_req *);
#define send_message 2
extern  int * send_message_1(SendMessageRequest *, CLIENT *);
extern  int * send_message_1_svc(SendMessageRequest *, struct svc_req *);
#define fetch_message 3
extern  FetchMessageResponse * fetch_message_1(FetchMessageRequest *, CLIENT *);
extern  FetchMessageResponse * fetch_message_1_svc(FetchMessageRequest *, struct svc_req *);
#define deregister_client 4
extern  int * deregister_client_1(RegisterRequest *, CLIENT *);
extern  int * deregister_client_1_svc(RegisterRequest *, struct svc_req *);
extern int messaging_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define register_client 1
extern  int * register_client_1();
extern  int * register_client_1_svc();
#define send_message 2
extern  int * send_message_1();
extern  int * send_message_1_svc();
#define fetch_message 3
extern  FetchMessageResponse * fetch_message_1();
extern  FetchMessageResponse * fetch_message_1_svc();
#define deregister_client 4
extern  int * deregister_client_1();
extern  int * deregister_client_1_svc();
extern int messaging_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Message (XDR *, Message*);
extern  bool_t xdr_MessageArray (XDR *, MessageArray*);
extern  bool_t xdr_RegisterRequest (XDR *, RegisterRequest*);
extern  bool_t xdr_SendMessageRequest (XDR *, SendMessageRequest*);
extern  bool_t xdr_FetchMessageRequest (XDR *, FetchMessageRequest*);
extern  bool_t xdr_FetchMessageResponse (XDR *, FetchMessageResponse*);

#else /* K&R C */
extern bool_t xdr_Message ();
extern bool_t xdr_MessageArray ();
extern bool_t xdr_RegisterRequest ();
extern bool_t xdr_SendMessageRequest ();
extern bool_t xdr_FetchMessageRequest ();
extern bool_t xdr_FetchMessageResponse ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MESSAGING_H_RPCGEN */
